###
# Get Supplier
GET http://localhost:3000/api/supplier

###
# Create Supplier
POST http://localhost:3000/api/supplier
Content-Type: application/json

{
    "name_supplier": "1",
    "address_supplier": "1",
    "phone_supplier": "1"
}

###
# Get Supplier by id
GET http://localhost:3000/api/supplier/1

###
# Update Supplier by id
PATCH http://localhost:3000/api/supplier/1  
Content-Type: application/json

{
    "name_supplier": "Firdan",
    "address_supplier": "Sadanaland No.45",
    "phone_supplier": "085284070404"
}

####
# Delete Supplier by id
DELETE http://localhost:3000/api/supplier/6

###
# Get Rack
GET http://localhost:3000/api/rack

###
# Create Rack
POST http://localhost:3000/api/rack
Content-Type: application/json

{
    "rack_no": "A3"
}

###
# Get Rack by id
GET http://localhost:3000/api/rack/3

###
# Update Rack by id
PATCH http://localhost:3000/api/rack/3  
Content-Type: application/json

{
    "rack_no": "A2"
}

####
# Delete Rack by id
DELETE http://localhost:3000/api/rack/2

###
# Get Part
GET http://localhost:3000/api/part

###
# Get Part by id
GET http://localhost:3000/api/part/1

###
# Create Part
POST http://localhost:3000/api/part
Content-Type: application/json

{
    "part_name": "A1",
    "part_uniq": "A11",
    "mst_rackId": 1
}

###
# Update Part by id
PATCH http://localhost:3000/api/part/1  
Content-Type: application/json

{
    "part_name": "A2",
    "part_uniq": "A13",
    "mst_rackId": 1
}

####
# Delete Part by id
DELETE http://localhost:3000/api/part/2

###
# Get tb_wo
GET http://localhost:3000/api/wo

###
# Get tb_wo by id
GET http://localhost:3000/api/wo/2

###
# Create tb_wo
POST http://localhost:3000/api/wo
Content-Type: application/json

{
    "qty_kbn": 1,
    "qty_order": 2,
    "date_input": "2023-05-24T23:51:57.000Z",
    "mst_partId" : 1,
    "mst_supplierId" : 1
}

###
# Update tb_wo by id
PATCH http://localhost:3000/api/wo/5 
Content-Type: application/json

{
    "qty_kbn": 4,
    "qty_order": 2,
    "date_input": "2023-05-24T23:51:57.000Z",
    "mst_partId" : 1,
    "mst_supplierId" : 1
}

####
# Delete Wo by id
DELETE http://localhost:3000/api/wo/2

###
# Get tb_do
GET http://localhost:3000/api/do

###
# Get tb_do by id
GET http://localhost:3000/api/do/21

###
# Create tb_do
POST http://localhost:3000/api/do
Content-Type: application/json

{
    "qty_kbn": 1,
    "qty_order": 2,
    "no_truck": "N1234b",
    "date_input": "2023-05-24T23:51:57.000Z",
    "mst_partId" : 1,
    "mst_supplierId" : 1
}

###
# Update tb_do by id
PATCH http://localhost:3000/api/do/20 
Content-Type: application/json

{
    "qty_kbn": 1181,
    "qty_order": 113,
    "no_truck": "N11111111b",
    "date_input": "2023-05-24T23:51:57.000Z",
    "mst_partId" : 1,
    "mst_supplierId" : 1
}

####
# Delete do by id
DELETE http://localhost:3000/api/do/21
